"Width first Tiny calculator"
<~~c.compile(c.asg)~~>

{

Expression  =
    (
        Term
        ( "+" | "-" )       <~~push(up.in)~~>
        Term
    )                       <~~
                            var t2 = pop()
                            var op = pop()
                            var t1 = pop()
                            println("calculating " + t1 + " " + op + " " + t2)
                            var res = (op=="+") ? t1 + t2 : t1 - t2
                            push(res)
                            ~~>
    |
    Term
    ;

Term        =
    (
        Factor
        ( "*" | "/" )       <~~push(up.in)~~>
        Factor
    )                       <~~
                            var t2 = pop()
                            var op = pop()
                            var t1 = pop()
                            println("calculating " + t1 + " " + op + " " + t2)
                            var res = (op=="*") ? t1 * t2 : t1 / t2
                            push(res)
                            ~~>
    |
    Factor
    ;

Factor      =
    (
        "("
        Expression
        ")"
    )
    |
    Number                 <~~push(parseFloat(up.in))~~>
    ;

Number      = ( "0" | Nonzero { "0" | Nonzero } )
              [ ( "." | "," ) { "0" | Nonzero } ] ;
Nonzero     = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

}

<~~println("\nRESULT: " + pop() + "\nFormula was: " + ltr.in)~~>

Expression
