/* Java recognition test.
 * Exercises constructs the grammar newly RECOGNIZES but does not implement: the
 * bitwise (& | ^ ~) and shift (<< >> >>>) operators, compound bitwise/shift
 * assignment (|= <<=), instanceof (with a pattern binding), the assert statement,
 * labeled statements with labeled break/continue, the synchronized statement, char
 * literals, hex/binary/floating-point/underscored/suffixed number literals and a
 * text block. Prefix ++/-- and unary + are genuinely lowered.
 *
 * Under a DEFAULT run this ABORTS at the first not-implemented construct with a clean
 * file:line message. Under -warn-unsupported every not-implemented construct warns and
 * the genuinely lowered parts (the class, the loops, prefix ++, the arithmetic) run;
 * Main.main self-checks those and exits with the failure count (0 when all pass). The
 * not-implemented values are inert (they stay undefined) and are never asserted on. **/

package com.example.util;

import java.util.List;

public class Main {
    static int fails = 0;

    static void check(String name, int got, int want) {
        if (got != want) {
            System.out.println("FAIL " + name + ": got " + got + " want " + want);
            Main.fails++;
        }
    }

    // Bit twiddling: every operator here is recognized but not implemented, so the
    // result is inert. The point is that a real-world bit-manipulation method PARSES.
    static int mixBits(int seed) {
        int mask = 0xFF;                 // hex literal
        int flags = 0b1010;              // binary literal
        int shifted = seed << 3;         // shift operator
        int masked = shifted & mask;     // bitwise and
        int combined = masked | flags;   // bitwise or
        int xored = combined ^ 0x0F;     // bitwise xor
        int inverted = ~xored;           // bitwise not
        flags |= 0b0100;                 // compound bitwise assignment
        flags <<= 1;                     // compound shift assignment
        return inverted >>> 2;           // unsigned right shift
    }

    public static void main(String[] args) {
        long big = 9_000_000_000L;       // underscored + suffixed long literal
        double ratio = 3.14;             // floating-point literal
        char grade = 'A';                // char literal

        // A text block (recognized, not implemented).
        String banner = """
            === report ===
            generated by Main""";

        // Genuine prefix ++/-- and unary + : these really run and are checked.
        int counter = 0;
        int first = ++counter;
        Main.check("pre-increment value", first, 1);
        Main.check("pre-increment side effect", counter, 1);
        int back = --counter;
        Main.check("pre-decrement value", back, 0);
        int pos = +5;
        Main.check("unary plus identity", pos, 5);

        // instanceof with a pattern binding (recognized, not implemented).
        Object o = "hello";
        if (o instanceof String s) {
            System.out.println("string branch (not reached: instanceof is inert)");
        }

        // assert with a message (recognized, not implemented).
        assert counter >= 0 : "counter must not be negative";

        // A labeled loop with labeled continue/break (recognized, not implemented; they
        // fall back to the plain innermost jump, so the loops still run and terminate).
        int visits = 0;
        search:
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                visits++;
                if (j == 1) {
                    continue search;
                }
                if (i == 2) {
                    break search;
                }
            }
        }

        // A synchronized statement (recognized, not implemented; the block still runs).
        Object lock = "lock";
        synchronized (lock) {
            int inert = Main.mixBits(5);
        }

        if (Main.fails == 0) {
            System.out.println("Java recognition test passed");
        }
        System.exit(Main.fails);
    }
}
