"Tiny C-ish language"
{

Program     = { Statement } ;
Statement   = "if" ParenExpr Statement
            | "if" ParenExpr Statement "else" Statement
            | "for" ParenExpr Statement
            | "while" ParenExpr Statement
            | "do" Statement "while" ParenExpr ";"
            | "{" { Statement } "}"
            | Expr ";"
            | ";" ;

ParenExpr   =  "(" Expr ")" ;

Expr        = Declaration | Assignment | Command | Test ;

Declaration = "var" ( Assignment | Id ) ;

Assignment  = Id "=" Expr ;

Test        = Comp ( "||" | "&&" ) Comp | Comp ;
Comp        = Sum ( "<" | ">" | "==" | "!=" ) Sum | Sum ;
Sum         = Term "+" Sum | Term "-" Sum | Term ;
Term        = ParenExpr | Command | Id | Int ;

Command     = Id "(" [ Parameter { "," Parameter } ] ")" ;
Parameter   = Command | Test ;

Id          = ( "a"..."z" | "A"..."Z" ) - { "a"..."z" | "A"..."Z" | "_" } + ;
Int         = "0" | "1"..."9" - { "0"..."9" } + ;

# The first option(s) of an OR must not be the beginning of a later option. Otherwise only the first option would be found and success would be returned.

}
Program
