:title("TLV Test") ;


:startRule(TLV) ;
:whitespace() ;

TLV           = InitialByte { TLVEntry } Preamble ;

InitialByte   = "\x00"..b"\xff" <~~ println(">" + up.in + "<") ~~> ;
TLVEntry      = :number(1, 0)("\x00"..b"\xff") <~~ println(">" + up.in + "<") ~~> ;
Preamble      = { "\x00"..b"\xff" } <~~ println(">" + up.in + "<") ~~> ;


:startScript(~~ c.compile(c.asg) ~~) ;
