:title("TLV Test") ;


:startRule(TLV) ;
:skip("") ;

TLV = "\x00"..b"\xff" <~~ println(">" + up.in + "<") ~~> { :number(1, 0)("\x00"..b"\xff") <~~ println(">" + up.in + "<") ~~> } { "\x00"..b"\xff" } <~~ println(">" + up.in + "<") ~~> ;


:startScript(~~ c.compile(c.asg) ~~) ;
