package abnf

import (
	_ "embed"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"time"

	"14.gy/mec/abnf/r"
	"github.com/llir/llvm/asm"
	"github.com/llir/llvm/ir"
)

// ----------------------------------------------------------------------------
// Frozen script execution (the goja free bootstrap)
//
// In frozen mode (-frozen) the annotation scripts of the grammars are not run
// by goja. Instead:
//
//  1. A script is parsed with the frozen a-grammar of languages/metajs-to-llvm-ir.abnf
//     (jsAgrammar, generated into jsagrammar.go by -freeze). This is a pure Go
//     parse.
//  2. The resulting ASG is walked bottom up (the normal compile walk). Every
//     tag of that walk is one of the metajs-to-llvm-ir tag scripts - and those were
//     compiled to IR once, at freeze time, by the grammar itself running under
//     goja. The snapshot (jsbootstrap.ll) contains one closure per distinct
//     tag source, plus the emitter library. Executing them on the llvm.Run
//     machine emits the IR module of the script.
//  3. The emitted module is executed on a MetaJS runtime (jsrt.go) whose root
//     bindings are the host API of the metacompiler: up/ltr, the stacks, c,
//     abnf and llvm. Arbitrary Go values (rules, llir builder objects) flow
//     through the handle table, and closures the scripts push onto the stacks
//     survive as IR function handles.
//
// goja is only needed to (re)create the snapshot with -freeze.

// UseFrozenScripts switches the parser and compiler script subsystems from
// goja to the frozen MetaJS bootstrap. Set by the -frozen command line flag.
var UseFrozenScripts = false

// jsBootstrapLL is the frozen IR snapshot: the tag scripts and the emitter
// library of languages/metajs-to-llvm-ir.abnf, compiled by itself. (Re)generated by
// 'mec -freeze'.
//
//go:embed jsbootstrap.ll
var jsBootstrapLL string

// The marker that separates the reusable emitter library of the metajs-to-llvm-ir
// start script from its goja driver tail.
const frozenDriverMarker = "// ===== goja driver ====="

// fkernel holds everything that all frozen engines share: the frozen a-grammar,
// the bootstrap module, and the cache of compiled scripts. Compiled script
// modules are context free (all bindings live in the runtimes), so one cache
// serves every engine.
type fkernel struct {
	jsG      *r.Rules
	bootMod  *ir.Module
	compiled map[string]*ir.Module // script source -> emitted module
}

var theKernel *fkernel

func frozenKernel() *fkernel {
	if theKernel != nil {
		return theKernel
	}
	if jsAgrammar == nil || len(jsBootstrapLL) == 0 {
		panic("frozen mode needs the bootstrap snapshot: run 'mec -freeze languages/metajs-to-llvm-ir.abnf' and rebuild")
	}
	mod, err := asm.ParseString("jsbootstrap.ll", jsBootstrapLL)
	if err != nil {
		panic("cannot parse the frozen bootstrap module: " + err.Error())
	}
	theKernel = &fkernel{
		jsG:      jsAgrammar,
		bootMod:  mod,
		compiled: map[string]*ir.Module{},
	}
	return theKernel
}

// bootObject runs the bootstrap entry on the given runtime and returns the
// library handshake: {module: <the fresh output module>, tags: {source: closure}}.
func bootObject(rt *jsrt, ma *machine) (*ir.Module, *jsObject) {
	h := rt.callEntry(ma, "jsmain", 0)
	obj, ok := rt.unwrap(h).(*jsObject)
	if !ok {
		panic("frozen bootstrap did not return its {module, tags} object")
	}
	mod, ok := obj.props["module"].(*ir.Module)
	if !ok {
		panic("frozen bootstrap returned no module")
	}
	tags, ok := obj.props["tags"].(*jsObject)
	if !ok {
		panic("frozen bootstrap returned no tags")
	}
	return mod, tags
}

// walkEngine is the scriptEngine that compiles one annotation script: the walk
// over the script ASG executes the frozen metajs-to-llvm-ir tag closures, which
// emit the module of the script.
type walkEngine struct {
	rt    *jsrt
	tags  *jsObject
	ltr   map[string]r.Object
	curUp map[string]r.Object
}

func (we *walkEngine) Ltr() map[string]r.Object { return we.ltr }

func (we *walkEngine) RunTagCode(tag *r.Rule, name string, upStream map[string]r.Object, localASG *r.Rules, slot int, depth int) (r.Object, bool) {
	if !(slot < len(*tag.CodeChilds)) {
		return nil, false
	}
	code := (*tag.CodeChilds)[slot].String
	cl, ok := we.tags.props[code]
	if !ok {
		panic("frozen bootstrap snapshot is stale: unknown compiler tag script:\n" + code)
	}
	defer func() {
		if err := recover(); err != nil {
			panic(fmt.Sprintf("%s\nError was while compiling a script, in the emitter tag: '%s'", err, code))
		}
	}()
	we.curUp = upStream
	we.rt.setRootVar("up", upStream)
	saved := we.rt.retSlot
	we.rt.retSlot = jsUndef
	we.rt.call(cl, jsUndef, nil)
	we.rt.retSlot = saved
	return nil, true // The emitter tags work by side effect; their completion is not used.
}

// newWalkRuntime creates the runtime for one script compilation: the bootstrap
// library sees the compile walk (up, push, pop) and the emitter hosts.
func newWalkRuntime() (*jsrt, *walkEngine) {
	we := &walkEngine{ltr: map[string]r.Object{"in": ""}}
	bindings := frozenBaseBindings(false)
	bindings["llvm"] = llvmFuncMap
	bindings["abnf"] = r.AbnfFuncMap
	bindings["up"] = nil // Replaced per tag below.
	// The bootstrap compiles TAG SCRIPTS here: they never get js_srcpos
	// markers (stmtPos in lib/compile-core.js reads c.tracing), their
	// positions would point into tag text, not into the traced program.
	bindings["c"] = map[string]r.Object{"tracing": false}
	bindings["pop"] = jsHostFunc("pop", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		stack, ok := we.curUp["stack"].([]interface{})
		if !ok || len(stack) == 0 {
			return jsNull
		}
		res := stack[len(stack)-1]
		we.curUp["stack"] = stack[:len(stack)-1]
		return rt.importGoValue(res)
	})
	bindings["push"] = jsHostFunc("push", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		stack, ok := we.curUp["stack"].([]interface{})
		if !ok {
			stack = []interface{}{}
		}
		we.curUp["stack"] = append(stack, argAt(args, 0))
		return jsUndef
	})
	rt := newJSRT(bindings)
	we.rt = rt
	return rt, we
}

// compileScript turns one annotation script into an IR module (cached by source).
func (k *fkernel) compileScript(code string, name string) *ir.Module {
	if mod, ok := k.compiled[code]; ok {
		return mod
	}

	asg, err := ParseWithAgrammar(k.jsG, code, name, &Parseropts{PreventDefaultOutput: true})
	if err != nil {
		panic(fmt.Sprintf("frozen: cannot parse script %s: %s\nScript was: %s", name, err, code))
	}

	rt, we := newWalkRuntime()
	maBoot := rt.attach(k.bootMod)
	mod, tags := bootObject(rt, maBoot)
	we.tags = tags

	co := &compiler{eng: we, fileName: name}
	co.compile(asg, 0, 0)

	k.compiled[code] = mod
	return mod
}

// runScript executes a compiled script module on the given runtime in the given
// scope and returns its completion value (the value of the last expression
// statement, like a goja Run would return).
func runScriptModule(rt *jsrt, ma *machine, scope uint64) interface{} {
	saved := rt.retSlot
	rt.retSlot = jsUndef
	h := ma.callByName("jsrun", []uint64{scope, rt.wrap(&jsArray{})})
	res := rt.unwrap(h)
	rt.retSlot = saved
	return res
}

// frozenBaseBindings are the host globals that every frozen context provides
// (the MetaJS standard set plus console output honoring the quiet flags).
func frozenBaseBindings(preventDefaultOutput bool) map[string]interface{} {
	b := standardJSBindings()
	if preventDefaultOutput {
		noop := jsHostFunc("noop", func(rt *jsrt, this uint64, args []interface{}) interface{} { return jsUndef })
		b["println"] = noop
		b["print"] = noop
		b["printf"] = noop
	}
	b["sleep"] = jsHostFunc("sleep", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		time.Sleep(time.Duration(rt.toNumber(argAt(args, 0))) * time.Millisecond)
		return jsUndef
	})
	return b
}

// ----------------------------------------------------------------------------
// The frozen compiler engine (scriptEngine)

type frozenEngine struct {
	co *compiler
	rt *jsrt

	machines    map[*ir.Module]*machine
	sharedScope uint64 // All scripts of one compile run share their top level.

	ltrStream map[string]r.Object
	stack     []r.Object // The global stack (pushg/popg).
	curUp     map[string]r.Object

	cMap map[string]r.Object // The JS object 'c'.

	fileName             string
	preventDefaultOutput bool
	references           *references
}

func newFrozenEngine(co *compiler, asg *r.Rules, aGrammar *r.Rules, traceEnabled, preventDefaultOutput bool) *frozenEngine {
	eng := &frozenEngine{
		co:                   co,
		machines:             map[*ir.Module]*machine{},
		preventDefaultOutput: preventDefaultOutput,
	}
	// Scripts belong to the GRAMMAR: resolve include/load/store relative to
	// its :origin() stamp (like the goja engine's module names). Grammars
	// without one fall back to the compile target (RunTagCode's lazy init).
	eng.fileName = r.GetOrigin(aGrammar)
	eng.ltrStream = map[string]r.Object{
		"in":    "",
		"stack": &eng.stack,
	}
	eng.cMap = map[string]r.Object{
		"asg":          asg,
		"agrammar":     aGrammar,
		"ABNFagrammar": AbnfAgrammar,
		"compile": func(asg *r.Rules, slot int, traceEnabled bool) map[string]r.Object {
			return eng.co.compile(asg, slot, 0)
		},
		"parse": func(agrammar *r.Rules, srcCode string, options *Parseropts) *r.Rules {
			if options == nil {
				options = &Parseropts{}
			}
			productions, err := ParseWithAgrammar(agrammar, srcCode, eng.fileName, options)
			if err != nil {
				panic(err)
			}
			return productions
		},
		"compileRunStartScript": func(asg *r.Rules, aGrammar *r.Rules, slot int, traceEnabled bool) interface{} {
			return compileASGInternal(asg, aGrammar, eng.fileName, slot, traceEnabled, eng.preventDefaultOutput)
		},
		// True when -trace/-cfg collect source positions: the compilers then
		// emit js_srcpos statement markers (see lib/compile-core.js stmtPos).
		"tracing": TraceMarkersWanted(),
		// Import policy + source positions for clean grammar errors (mirrors the
		// goja c map in commonscript.go).
		"warnImports":     WarnUnresolvedImports,
		"warnUnsupported": WarnUnsupported,
		"file":            traceSrcName,
		"lineOf":          func(pos int) int { return lineOfPos(pos) },
	}

	bindings := frozenBaseBindings(preventDefaultOutput)
	bindings["llvm"] = llvmFuncMap
	bindings["abnf"] = r.AbnfFuncMap
	bindings["c"] = eng.cMap
	bindings["ltr"] = eng.ltrStream
	bindings["up"] = nil // Replaced per tag execution.
	bindings["append"] = func(t []interface{}, v ...interface{}) interface{} {
		tmp := append(t, v...)
		return &tmp
	}
	bindings["unescape"] = r.Unescape
	bindings["unescapeTilde"] = UnescapeTilde
	// correctReferencesAndIDs is a global (not part of abnf.*): it links a freshly
	// built a-grammar so it can be compiled directly - resolving each Identifier to its
	// Production and giving each Tag a UID. See references.correctReferencesAndIDs.
	bindings["correctReferencesAndIDs"] = func(agrammar *r.Rules) {
		if eng.references == nil {
			eng.references = NewReferences()
		}
		eng.references.correctReferencesAndIDs(agrammar)
	}
	bindings["load"] = func(fileName string) string {
		dat, err := ioutil.ReadFile(eng.resolvePath(fileName))
		if err != nil {
			panic(err)
		}
		return string(dat)
	}
	bindings["store"] = func(fileName, data string) {
		if err := ioutil.WriteFile(eng.resolvePath(fileName), []byte(data), 0644); err != nil {
			panic(err)
		}
	}
	bindings["moduleName"] = func() string { return eng.fileName }
	bindings["include"] = jsHostFunc("include", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		fileName := rt.toString(argAt(args, 0))
		if fileName == "" {
			return false
		}
		resolved := eng.resolvePath(fileName)
		dat, err := ioutil.ReadFile(resolved)
		if err != nil {
			panic(err)
		}
		mod := frozenKernel().compileScript(string(dat), resolved)
		// The included file runs AS its own module (goja names each program
		// after its file): a nested include(), load() or moduleName() inside
		// it resolves relative to the included file, not to the includer -
		// resolving everything against the grammar dir broke nested includes.
		savedFile := eng.fileName
		eng.fileName = resolved
		defer func() { eng.fileName = savedFile }()
		runScriptModule(rt, eng.machineFor(mod), eng.sharedScope)
		return true
	})

	eng.rt = newJSRT(bindings)
	eng.sharedScope = eng.rt.newScopeHandle(nil)

	// eval compiles the string like any other script and runs it in the shared
	// scope, so evaluated code sees (and can create) the script globals.
	eng.rt.setRootVar("eval", jsHostFunc("eval", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		mod := frozenKernel().compileScript(rt.toString(argAt(args, 0)), "eval")
		return runScriptModule(rt, eng.machineFor(mod), eng.sharedScope)
	}))

	// The stack functions work on the upStream of the currently running tag.
	eng.rt.setRootVar("pop", jsHostFunc("pop", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		stack, ok := eng.curUp["stack"].([]interface{})
		if !ok || len(stack) == 0 {
			return jsNull
		}
		res := stack[len(stack)-1]
		eng.curUp["stack"] = stack[:len(stack)-1]
		return rt.importGoValue(res)
	}))
	eng.rt.setRootVar("push", jsHostFunc("push", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		stack, ok := eng.curUp["stack"].([]interface{})
		if !ok {
			stack = []interface{}{}
		}
		eng.curUp["stack"] = append(stack, argAt(args, 0))
		return jsUndef
	}))
	eng.rt.setRootVar("popg", jsHostFunc("popg", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		if len(eng.stack) == 0 {
			return jsNull
		}
		res := eng.stack[len(eng.stack)-1]
		eng.stack = eng.stack[:len(eng.stack)-1]
		return rt.importGoValue(res)
	}))
	eng.rt.setRootVar("pushg", jsHostFunc("pushg", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		eng.stack = append(eng.stack, argAt(args, 0))
		return jsUndef
	}))

	return eng
}

func (eng *frozenEngine) resolvePath(fileName string) string {
	return filepath.Dir(eng.fileName) + string(os.PathSeparator) + filepath.Clean(fileName)
}

func (eng *frozenEngine) machineFor(mod *ir.Module) *machine {
	ma, ok := eng.machines[mod]
	if !ok {
		ma = eng.rt.attach(mod)
		eng.machines[mod] = ma
	}
	return ma
}

func (eng *frozenEngine) Ltr() map[string]r.Object { return eng.ltrStream }

func (eng *frozenEngine) RunTagCode(tag *r.Rule, name string, upStream map[string]r.Object, localASG *r.Rules, slot int, depth int) (r.Object, bool) {
	if !(slot < len(*tag.CodeChilds)) {
		return nil, false
	}
	if eng.fileName == "" {
		eng.fileName = eng.co.fileName
	}
	code := (*tag.CodeChilds)[slot].String
	defer func() {
		if err := recover(); err != nil {
			panic(fmt.Sprintf("%s\nError was in %s, Code: '%s'", err, tag.ToString(), code))
		}
	}()

	mod := frozenKernel().compileScript(code, name)
	ma := eng.machineFor(mod)

	eng.cMap["localAsg"] = localASG
	savedUp := eng.curUp
	eng.curUp = upStream
	eng.rt.setRootVar("up", upStream)

	res := runScriptModule(eng.rt, ma, eng.sharedScope)

	eng.curUp = savedUp
	eng.rt.setRootVar("up", savedUp)

	return eng.exportCompletion(res), true
}

// exportCompletion converts a script completion value into the plain Go form
// that CompileASG() expects (what a goja Export would have produced).
func (eng *frozenEngine) exportCompletion(v interface{}) r.Object {
	switch t := v.(type) {
	case *[]r.Object: // ltr.stack: a live pointer to the global stack.
		return append([]interface{}{}, *t...)
	case *jsArray:
		out := make([]interface{}, len(t.elems))
		for i, e := range t.elems {
			out[i] = eng.exportCompletion(e)
		}
		return out
	case jsUndefT, jsNullT:
		return nil
	default:
		return eng.rt.toGoNatural(v)
	}
}

// ----------------------------------------------------------------------------
// The frozen parser script runner (scriptRuleRunner)

type frozenParserScript struct {
	pa *parser

	rt          *jsrt
	machines    map[*ir.Module]*machine
	bootTags    *jsObject
	sharedScope uint64
	stack       []r.Object // Survives between the :script() calls of one parse run.
	cMap        map[string]r.Object
	fileName    string      // The grammar's :origin() (fallback: the parsed file); include/load/store resolve relative to it.
	references  *references // For the correctReferencesAndIDs binding.
}

func newFrozenParserScript(pa *parser) *frozenParserScript {
	return &frozenParserScript{pa: pa}
}

func (ps *frozenParserScript) resolvePath(fileName string) string {
	return filepath.Dir(ps.fileName) + string(os.PathSeparator) + filepath.Clean(fileName)
}

// init builds the runtime lazily: most grammars have no :script() rules.
// The bindings mirror the goja side (NewCommonScript + the parser c entries):
// a global that exists under goja but not here is a latent "variable not
// defined" abort that only fires under -frozen.
func (ps *frozenParserScript) init() {
	if ps.rt != nil {
		return
	}
	ps.machines = map[*ir.Module]*machine{}
	ps.fileName = r.GetOrigin(ps.pa.agrammar)
	if ps.fileName == "" {
		ps.fileName = ps.pa.fileName
	}
	ps.cMap = map[string]r.Object{
		"getSrc": func() string { return ps.pa.Src },
		"setSrc": func(src string) { ps.pa.Src = src },
		"getSdx": func() int { return ps.pa.Sdx },
		"setSdx": func(sdx int) { ps.pa.Sdx = sdx },
		"peek": func(offset int) int {
			pos := ps.pa.Sdx + offset
			if pos < 0 || pos >= len(ps.pa.Src) {
				return -1
			}
			return int(ps.pa.Src[pos])
		},
		// The common c entries of the goja side (commonscript.go).
		"parse": func(agrammar *r.Rules, srcCode string, options *Parseropts) *r.Rules {
			if options == nil {
				options = &Parseropts{}
			}
			productions, err := ParseWithAgrammar(agrammar, srcCode, ps.fileName, options)
			if err != nil {
				panic(err)
			}
			return productions
		},
		"compileRunStartScript": func(asg *r.Rules, aGrammar *r.Rules, slot int, traceEnabled bool) interface{} {
			return compileASGInternal(asg, aGrammar, ps.fileName, slot, traceEnabled, false)
		},
		"ABNFagrammar":    AbnfAgrammar,
		"tracing":         TraceMarkersWanted(),
		"warnImports":     WarnUnresolvedImports,
		"warnUnsupported": WarnUnsupported,
		"file":            traceSrcName,
		"lineOf":          func(pos int) int { return lineOfPos(pos) },
	}
	bindings := frozenBaseBindings(ps.pa.opts.PreventDefaultOutput)
	bindings["llvm"] = llvmFuncMap
	bindings["abnf"] = r.AbnfFuncMap
	bindings["c"] = ps.cMap
	bindings["append"] = func(t []interface{}, v ...interface{}) interface{} {
		tmp := append(t, v...)
		return &tmp
	}
	bindings["unescape"] = r.Unescape
	bindings["unescapeTilde"] = UnescapeTilde
	bindings["correctReferencesAndIDs"] = func(agrammar *r.Rules) {
		if ps.references == nil {
			ps.references = NewReferences()
		}
		ps.references.correctReferencesAndIDs(agrammar)
	}
	bindings["load"] = func(fileName string) string {
		dat, err := ioutil.ReadFile(ps.resolvePath(fileName))
		if err != nil {
			panic(err)
		}
		return string(dat)
	}
	bindings["store"] = func(fileName, data string) {
		if err := ioutil.WriteFile(ps.resolvePath(fileName), []byte(data), 0644); err != nil {
			panic(err)
		}
	}
	bindings["moduleName"] = func() string { return ps.fileName }
	bindings["include"] = jsHostFunc("include", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		fileName := rt.toString(argAt(args, 0))
		if fileName == "" {
			return false
		}
		resolved := ps.resolvePath(fileName)
		dat, err := ioutil.ReadFile(resolved)
		if err != nil {
			panic(err)
		}
		mod := frozenKernel().compileScript(string(dat), resolved)
		ma, ok := ps.machines[mod]
		if !ok {
			ma = ps.rt.attach(mod)
			ps.machines[mod] = ma
		}
		// The included file runs as its own module, like in the compiler engine.
		savedFile := ps.fileName
		ps.fileName = resolved
		defer func() { ps.fileName = savedFile }()
		runScriptModule(rt, ma, ps.sharedScope)
		return true
	})
	bindings["pop"] = jsHostFunc("pop", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		if len(ps.stack) == 0 {
			return jsNull
		}
		res := ps.stack[len(ps.stack)-1]
		ps.stack = ps.stack[:len(ps.stack)-1]
		return rt.importGoValue(res)
	})
	bindings["push"] = jsHostFunc("push", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		ps.stack = append(ps.stack, argAt(args, 0))
		return jsUndef
	})

	ps.rt = newJSRT(bindings)
	ps.sharedScope = ps.rt.newScopeHandle(nil)

	ps.rt.setRootVar("eval", jsHostFunc("eval", func(rt *jsrt, this uint64, args []interface{}) interface{} {
		mod := frozenKernel().compileScript(rt.toString(argAt(args, 0)), "eval")
		ma, ok := ps.machines[mod]
		if !ok {
			ma = ps.rt.attach(mod)
			ps.machines[mod] = ma
		}
		return runScriptModule(rt, ma, ps.sharedScope)
	}))

	// The grammar that parses the scripts has :script() rules itself (the
	// keyword boundary check). Their compiled closures come precompiled with
	// the bootstrap snapshot, which breaks the recursion.
	maBoot := ps.rt.attach(frozenKernel().bootMod)
	_, ps.bootTags = bootObject(ps.rt, maBoot)
}

func (ps *frozenParserScript) HandleScriptRule(rule *r.Rule, localProductions *r.Rules, depth int) *r.Rule {
	ps.init()
	code := (*rule.CodeChilds)[0].String
	ps.cMap["localAsg"] = localProductions

	saved := ps.rt.retSlot
	ps.rt.retSlot = jsUndef
	var completion interface{}
	if cl, ok := ps.bootTags.props[code]; ok {
		// A script of the frozen js grammar itself: run its precompiled closure.
		ps.rt.call(cl, jsUndef, nil)
		completion = ps.rt.retSlot
	} else {
		mod := frozenKernel().compileScript(code, ps.pa.fileName+":parserCommand")
		ma, ok := ps.machines[mod]
		if !ok {
			ma = ps.rt.attach(mod)
			ps.machines[mod] = ma
		}
		completion = runScriptModule(ps.rt, ma, ps.sharedScope)
	}
	ps.rt.retSlot = saved

	if res, ok := completion.(*r.Rule); ok {
		return res
	}
	return nil
}
